Project 1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p1/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Address__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>Street name</description>
    <label>Street Name</label>
    <type>TextArea</type>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Zip Code</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/classes/AccountLookupEditControllerwrappernonfunctional.cls
public with sharing class AccountLookupEditController {
    //public list<Contact> contList {get;set;}
    //public list<Address__c> addList{get;set;}

    public list<Wrapper> wrapperList {get;set;}

    public AccountLookupEditController(){
        id uid = UserInfo.getUserId();
        for(Contact c : [SELECT FirstName, LastName, MailingStreet, MailingCity, MailingState, MailingPostalCode, OwnerId FROM Contact WHERE OwnerId = :uid]){
            Wrapper con = new Wrapper();
            con.cont = c;
            wrapperList.add(con);
        }
        for(Address__c a : [SELECT Street_Name__c, City__c, State__c, Zip_Code__c FROM Address__c]){
            Wrapper addr = new Wrapper();
            addr.add = a;
            wrapperList.add(addr);
            }
    }

   /* public AccountLookupEditController() {
        id uid = UserInfo.getUserId();
        contList = [SELECT FirstName, LastName, MailingStreet, MailingCity, MailingState, MailingPostalCode, OwnerId FROM Contact WHERE OwnerId = :uid];
        addList = [SELECT Street__c, City__c, State__c, Zip_Code__c FROM Address__c];
    }

    public void contSave(){
        upsert cont;
    }*/
    
    public with sharing class wrapper {
    Public Contact cont {get;set;}
    Public Address__c add {get;set;}
    }
    
}