Project 1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p1/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State</description>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Address__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>Street name</description>
    <label>Street Name</label>
    <type>TextArea</type>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Zip Code</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/classes/AccountLookupEditController.cls
public class AccountLookupEditController {
    public List<List<SObject>> contList {get;set;}
    public list<Contact> contactList {get; set;}
    public List<Address__c> addList {get;set;}

    public AccountLookupEditController() {
        String uName = UserInfo.getName();
        contList = [FIND :uName In All FIELDS Returning Contact(FirstName, LastName, MailingStreet, MailingCity, MailingState, MailingPostalCode, OwnerId),
                                         Address__c(Street_Name__c, City__c, State__c, Zip_Code__c)];
        //[SELECT FirstName, LastName, MailingStreet, MailingCity, MailingState, MailingPostalCode, OwnerId FROM Contact WHERE (FirstName + LastName Like :uName)];
        contactList = contList[0];
        system.debug(contactList);
        addList = contList[1];
        system.debug(addList);
    }

    public void contSave(){
        
        upsert contactList;
        upsert addList;
    }
}