Project 1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project 1/force-app/main/default/objects/Mail__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Tracking Number</label>
    <type>AutoNumber</type>
</CustomField>

p1/force-app/main/default/classes/PackageTrackerController.cls
public class PackageTrackerController {
    public list<Mail__c> Tracking{get;set;}   
    public string Tnumber{get;set;}
    
    public PackageTrackerController(){
    
           Tracking = [SELECT Name, Tracking_Number__c, Delivery_status__c FROM Mail__c where Tracking_Number__c= :Tnumber];
    
            system.debug(Tracking);

        }
    
        public pagereference TrackingInfo()
        {
    		Tracking = [SELECT Name, Tracking_Number__c, Delivery_status__c FROM Mail__c where Tracking_Number__c= :Tnumber];
            system.debug('Value of Tracking' + Tracking);
            return null;
        }
    
    }